### PR TITLE
Support update hook for DummyTaskDefinition (resolves #140)

### LINKED ISSUE #140: Updates to DummyTaskDefinition break the stack and prevent future updates
If you try to update any attribute on the DummyTaskDefinition resource (for example, the optional family prop), then it fails with this error:

```
5:14:45 AM | UPDATE_FAILED        | Custom::BlueGreenService                  | EcsServiceCustomResource5EDA8C27
CustomResource attribute error: Vendor response doesn't contain taskDefinition.taskDefinitionArn key in object arn:aws:cloudformation:us-east-1:768404655438:stack/EcsTaggingTest/91a55fa0-4b94-11ec-a731-0eacf7b0a8db|DummyTaskDefinitionE3D9D432|fcad085b-b5a2-4a25-bbad-a66a696a7803 in S3 bucke
t cloudformation-custom-resource-storage-useast1
```

The DummyTaskDefinition isn't really intended to be used / updated, so it looks like updates weren't intended to be support.  However, when this happens, it triggers a rollback causing CloudFormation to call update on the custom resource again, leaving it in this broken state.  After this happens, subsequent deployments to the stack fail, and you can't really recover without updating the custom resource.

This can happen unintentionally during a refactor where the node address changes, because the node address is the default value for the optional family property.

### PR DESCRIPTION
**Pull request by cuperman**
Resolves issue: #140 

Fix: Create an onUpdate hook that calls `registerTaskDefinition`, as it does on the onCreate hook.  This causes lets CloudFormation know that the resource was replaced so that it can clean up the old resource.  This resolves the issue by having the task definition attributes on updates so that `Fn::GetAtt` intrinsic function continues to work.

### CODE REVIEW

**Comment by cuperman** [comment]
I was worried that updates to the dummy task definition would cause problems with the service since all updates require replacement.  The task definition / container / task is intended to be replaced by ones deployed with CodeDeploy, so I didn't want updates to the dummy task definition to interface and start running in the tasks.  But I tried various combinations of updates, and couldn't cause anything bad to happen.  Therefore, I decided to always replace on update.  This is more conventional, and I don't think it will cause problems with the blue/green CodeDeployed tasks.

**Comment by hupe1980** [comment]
Could we just return the physical resource id in a dummy update handler? Isn't that enough?

Maybe:
```typescript
const handleUpdate = (event) => {
   return {
      PhysicalResourceId: event.PhysicalResourceId, // taskdefArn
   }
}

```

**Comment by cuperman** [comment]
I know that calling `describeTaskDefinition` works, because it returns all the attributes, allowing the getattr functions to work.  I can try if returning just the physical id would do the same, but it may not.

but what is the point of deliberately suppressing updates on the resource?

**Comment by cuperman** [comment]
also, this custom resource uses `AwsCustomResource` which only supports `AwsSdkCall`s, not generic javascript functions.

**Comment by cuperman** [comment]
This is the simplest way to fix the issue and keep the existing behavior where updates are suppressed:

```ts
const taskDefinition = new AwsCustomResource(this, 'DummyTaskDefinition', {
  resourceType: 'Custom::DummyTaskDefinition',
  onCreate: {
    service: 'ECS',
    action: 'registerTaskDefinition',
    parameters: {
      requiresCompatibilities: ['FARGATE'],
      family: this.family,
      executionRoleArn: this.executionRole.roleArn,
      networkMode: NetworkMode.AWS_VPC,
      cpu: '256',
      memory: '512',
      containerDefinitions: [
        {
          name: this.containerName,
          image: props.image,
          portMappings: [
            {
              hostPort: this.containerPort,
              protocol: 'tcp',
              containerPort: this.containerPort,
            },
          ],
        },
      ],
    },
    physicalResourceId: PhysicalResourceId.fromResponse('taskDefinition.taskDefinitionArn'),
  },
  onUpdate: {
    service: 'ECS',
    action: 'describeTaskDefinition',
    parameters: {
      taskDefinition: new PhysicalResourceIdReference(),
    },
    physicalResourceId: PhysicalResourceId.fromResponse('taskDefinition.taskDefinitionArn'),
  },
  onDelete: {
    service: 'ECS',
    action: 'deregisterTaskDefinition',
    parameters: {
      taskDefinition: new PhysicalResourceIdReference(),
    },
  },
  policy: AwsCustomResourcePolicy.fromStatements([
    new PolicyStatement({
      effect: Effect.ALLOW,
      actions: ['ecs:RegisterTaskDefinition', 'ecs:DescribeTaskDefinition', 'ecs:DeregisterTaskDefinition'],
      resources: ['*'],
    }),
    new PolicyStatement({
      effect: Effect.ALLOW,
      actions: ['iam:PassRole'],
      resources: [this.executionRole.roleArn],
    }),
  ]),
});
```

I did some testing and couldn't find a negative impact of actually updating the resource, so I submitted the code the updates/replaces the resource instead of suppressing updates.  Let me know what you would prefer.  I can resubmit with changes.

Check out the initial commit on this PR and see what you think about the `allowUpdates` property.  Or we can keep things simple and make the change above.

**Comment by hupe1980** [comment]
You've convinced me.  😃 That's okay.

**Review by hupe1980 — APPROVED** [review]
LGTM! Thx

**Pull request merged**
