### PR TITLE
Upgrade nodejs runtime to 16.x (v2 branch)

### PR DESCRIPTION
**Pull request by mbp**
Node.js 16.x runtime has been available since May 2022: https://aws.amazon.com/blogs/compute/node-js-16-x-runtime-now-available-in-aws-lambda/

Node.js 14.x support is ending in 6 months: https://github.com/nodejs/release#release-schedule
Node.js 12.x support has already ended.

In this PR, I update all Lambda functions to use 16.x runtime. I also had to upgrade aws-cdk-lib minimum dependency to 2.28.0, since this version adds NODEJS_16_X on CustomResourceProviderRuntime.

### CODE REVIEW

**Comment by mbp** [comment]
@hupe1980 sorry to bother :-) Is it possible that you could take a look?

**Comment by mbp** [comment]
Friendly reminder @hupe1980. Now only 5 months for end of support for Node.js 14.x.

**Comment by kadishmal** [comment]
Hi @mbp! Just wanted to know if you are available to fix some comments for this PR? There are some errors if run as is. Can you rebase your branch from `cdk2` branch?

**Comment by mbp** [comment]
@kadishmal sorry, I am not available to do the changes. I had to stop using this project because of lack of updates.

**Comment by kadishmal** [comment]
@mbp, sure, I've made changes to fix the issues.

**Pull request merged**
