### PR TITLE
Support custom environment variables in a pull request check

### PR DESCRIPTION
**Pull request by mbp**
When a pull request check build has a custom environment variable, the Lambda approving the pull request would fail due to an unknown environment variable. I simply removed the error handling. The environment variables that are unknown, cause no harm.

### CODE REVIEW

**Comment by hupe1980** [comment]
The hash values ​​always change. You can better exclude them from the snapshot:
https://github.com/cloudcomponents/cdk-constructs/blob/00cd4c0b31f7c9e0e565b4a85e0b2eeca3825ce7/packages/cdk-stripe-webhook/src/__tests__/stripe-webhook.test.ts#L16-L27

**Comment by mbp** [comment]
Ok, @hupe1980 - I think I got it now though, but build is again failing for different reasons.

I am not able to verify my changes on local machine (this repository is not very Windows friendly) :-( 

Can you help?

**Comment by hupe1980** [comment]
You can simply replace all expect(stack).toMatchCdkSnapshot() with
```typescript
// THEN
  expect(stack).toMatchCdkSnapshot({
    ignoreAssets: true,
  });
```
Then update the snapshots and you're done

**Comment by hupe1980** [comment]
You forgot to update the snapshots  before commit -> yarn test -u

**Review by hupe1980 — APPROVED** [review]
LGTM! Thx

**Pull request merged**
