### PR TITLE
expose the StaticWebsite distribution

### PR DESCRIPTION
**Pull request by joeflateau**
I want to be able to issue an invalidation after cdk finishes but I need to be able to output the distribution id. #57 explains how to add an output, but without access to the underlying distribution you can't output it.

### CODE REVIEW

**Review by hupe1980 — APPROVED** [review]
LGTM! Thx

**Comment by joeflateau** [comment]
awesome! when do you do releases to npm? I don't see it on npm yet so I'm assuming it's not done through CI

**Comment by hupe1980** [comment]
A new version will be released today

**Comment by joeflateau** [comment]
for posterity, I add 

```
    new CfnOutput(this, "CloudfrontDistributionId", {
      value: website.distribution.distributionId,
    });```

to my stack

and 

```
      - name: invalidation
        run: |
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].Outputs[?OutputKey=='CloudfrontDistributionId'].OutputValue" --output text)
          aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*"```

to my github action and I get an invalidation on deploy 🎉

**Pull request merged**
